name: aoc_common

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  dartx:
    git:
      url: https://github.com/leisim/dartx.git
      ref: d3d4dcbede77aae8aec561a655efeebf6e972758
  kt_dart: ^0.7.0-dev.4

dev_dependencies:
  lint: ^1.1.0
