name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    container:
      image: google/dart:2.7

    strategy:
      matrix:
        day: ["01", "02", "03", "04", "05"]

    steps:
      - uses: actions/checkout@master
      - run: |
          cd day${{ matrix.day }}
          pub get
          pub run test
          dartanalyzer --fatal-infos --fatal-warnings .