name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    container:
      image: google/dart:2.7

    strategy:
      matrix:
        day: ["01", "02", "03", "04", "05", "06", "07"]

    steps:
      - uses: actions/checkout@master
      - run: pub get
        working-directory: day${{ matrix.day }}
      - name: Test
        run: pub run test
        working-directory: day${{ matrix.day }}
      - name: Lint
        run: dartanalyzer --fatal-infos --fatal-warnings .
        working-directory: day${{ matrix.day }}